### PR TITLE
Adding GPG key for apt repo

### PR DESCRIPTION
**Pull request by wilb**
Fixes https://github.com/ThoughtWorksInc/go-cookbook/issues/39

### CODE REVIEW

**Comment by mattcl** [comment]
Anyone know when this is going to be merged?

**Comment by ajeygore** [comment]
When is this gonna get merged? We are stuck with this.

**Comment by wilb** [comment]
You could always just clone my copy of it in the interim, the fix is difference.

https://github.com/wilb/go-cookbook/

**Comment by Tpbrown** [comment]
Sorry - been totally tied up w/project work.    This LGTM.  Thanks.

**Pull request merged**
